research_task:
  description: >
    Query blockchain forensic databases, security databases and websites to retrieve historical transaction data, blacklist status, 
    and connections to known scams interacting with {topic}.
  expected_output: >
    A structured dataset containing:
    - Transaction history (last 100 transactions)
    - Wallet labels (if it’s linked to scams or exchanges)
    - Connection to flagged entities
    - Risk assessment score (if available)
  agent: researcher
  
blacklist_check:
  description: >
    Check if {topic} appears in scam and blacklist databases or marked by you previously as a scam.
  expected_output: >
    A boolean value (True/False) and a list of sources where this wallet is flagged.
  agent: wallet_blacklist_checker

transaction_behavior_analysis:
  description: >
    Analyze the on-chain transaction patterns of {topic}.
  expected_output: >
    A report highlighting suspicious activity like frequent rug pulls, mixing services,
    high-volume transactions, or repeated flash loan usage.
  agent: transaction_behavior_analyst

sentiment_check:
  description: >
    Scan social media and blockchain forums for mentions of {topic}.
  expected_output: >
    A summary of public discussions and sentiment regarding this wallet.
  agent: sentiment_reputation_analyst

scam_likelihood_report:
  description: >
    Combine findings from all agents to calculate a scam likelihood score.
  expected_output: >
    A final risk assessment report with a score from 0-100 and a simple explanation.
  agent: risk_assessment_expert
