research_task:
  description: >
    Search for smart contract audits for {topic} and analyze their security.
  expected_output: >
    A summary of the security audits for {topic}, including:
    - List of audit sources (e.g., CertiK, Quantstamp, Trail of Bits)
    - Identified vulnerabilities (critical, high, medium, low)
    - Any unresolved security risks
    - Final audit ratings or security scores (if available)
    - If no audit exists, provide an assessment based on available security documentation.
  agent: security_auditor

sentiment_task:
  description: >
    Search online discussions and determine sentiment regarding {topic}.
  expected_output: >
    A sentiment analysis summary for {topic}, including:
    - General public perception (positive, neutral, or negative)
    - Key discussion points and concerns raised by the community
    - References to potential scams, rug pulls, or fraud
    - Popular sources of sentiment (Reddit, Twitter, Discord, Telegram)
    - A confidence level in the sentiment analysis.
  agent: sentiment_analyst
