blacklist_check:
  description: >
    Check if {topic} appears in scam and blacklist databases.
  expected_output: >
    A boolean value (True/False) and a list of sources where this wallet is flagged.
  agent: wallet_blacklist_checker

transaction_behavior_analysis:
  description: >
    Analyze the on-chain transaction patterns of {topic}.
  expected_output: >
    A report highlighting suspicious activity like frequent rug pulls, mixing services,
    high-volume transactions, or repeated flash loan usage.
  agent: transaction_behavior_analyst

sentiment_check:
  description: >
    Scan social media and blockchain forums for mentions of {topic}.
  expected_output: >
    A summary of public discussions and sentiment regarding this wallet.
  agent: sentiment_reputation_analyst

scam_likelihood_report:
  description: >
    Combine findings from all agents to calculate a scam likelihood score.
  expected_output: >
    A final risk assessment report with a score from 0-100 and a simple explanation.
  agent: risk_assessment_expert
